Controllers/FundraisersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CS451R_Fundraiser.Data;
using CS451R_Fundraiser.Models;
using Microsoft.AspNetCore.Identity;

namespace CS451R_Fundraiser.Controllers
{
    public class FundraisersController : Controller
    {
        private readonly CS451R_FundraiserContext _context;
        private readonly SignInManager<User> _signInManager;

        public FundraisersController(CS451R_FundraiserContext context, SignInManager<User> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }

        [HttpPost]
        [Route("Launch")]
        public IActionResult Launch()
        {
            return View("Launch");
        }
        
        
        // GET: Fundraisers
        public async Task<IActionResult> Index(string fundraiserCategory, string searchString)
        {
            if (_context.Fundraiser == null)
            {
                return Problem("Entity set 'CS451R_Fundraisers.Fundraisers'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> categoryQuery = from m in _context.Fundraiser
                                            orderby m.Category
                                            select m.Category;
            var fundraisers = from m in _context.Fundraiser
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                fundraisers = fundraisers.Where(s => s.Title!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(fundraiserCategory))
            {
                fundraisers = fundraisers.Where(x => x.Category == fundraiserCategory);
            }

            var fundraiserCategoryVM = new FundraiserCategoryViewModel
            {
                Categories = new SelectList(await categoryQuery.Distinct().ToListAsync()),
                Fundraisers = await fundraisers.ToListAsync()
            };

            return View(fundraiserCategoryVM);
        }

        // GET: Fundraisers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Fundraiser == null)
            {
                return NotFound();
            }

            var fundraiser = await _context.Fundraiser
                .FirstOrDefaultAsync(m => m.Id == id);
            var donations = _context.Donation
                                .Where(b => b.fundraiserId.Equals(fundraiser.Id));


            if (fundraiser == null)
            {
                return NotFound();
            }

            var fundraiserDonationvm = new FundraiserDonationViewModel
            {
                Fundraiser = fundraiser,
                Donations = await donations.ToListAsync()
            };

            return View(fundraiserDonationvm);
        }

        // GET: Fundraisers/Create
        public IActionResult Create()
        {
            if (User.Identity.IsAuthenticated) 
            {
                return View();
            }
            else
            {
                return Redirect("~/Identity/Account/Login");
            }
            
        }

        // POST: Fundraisers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,PostDate,Category,Goal")] Fundraiser fundraiser)
        {
            if (ModelState.IsValid)
            //if (true)
            {
                _context.Add(fundraiser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fundraiser);
        }

        // GET: Fundraisers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Fundraiser == null)
            {
                return NotFound();
            }

            var fundraiser = await _context.Fundraiser.FindAsync(id);
            if (fundraiser == null)
            {
                return NotFound();
            }
            if (User.Identity.IsAuthenticated)
            {
                return View(fundraiser);
            }
            else
            {
                return View("Invalid");
            }
        }

        // POST: Fundraisers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,PostDate,Category,Goal")] Fundraiser fundraiser)
        {
            if (id != fundraiser.Id)
            {
                return NotFound();
            }

            //foreach (var modelStateKey in ViewData.ModelState.Keys)
            //{
            //    var modelStateVal = ViewData.ModelState[modelStateKey];
            //    foreach (var error in modelStateVal.Errors)
            //    {
            //        var key = modelStateKey;
            //        var errorMessage = error.ErrorMessage;
            //        var exception = error.Exception;
            //        System.Diagnostics.Debug.WriteLine(key);
            //        System.Diagnostics.Debug.WriteLine(errorMessage);
            //        System.Diagnostics.Debug.WriteLine(exception);
            //    }
            //}

            if (ModelState.IsValid)
            //if (true)
            {
                try
                {
                    _context.Update(fundraiser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FundraiserExists(fundraiser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fundraiser);
        }

        // GET: Fundraisers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Fundraiser == null)
            {
                return NotFound();
            }

            var fundraiser = await _context.Fundraiser
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fundraiser == null)
            {
                return NotFound();
            }
            if (User.Identity.IsAuthenticated)
            {
                return View(fundraiser);
            }
            else
            {
                return View("Invalid");
            }
        }

        // POST: Fundraisers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Fundraiser == null)
            {
                return Problem("Entity set 'CS451R_FundraiserContext.Fundraiser'  is null.");
            }
            var fundraiser = await _context.Fundraiser.FindAsync(id);
            if (fundraiser != null)
            {
                _context.Fundraiser.Remove(fundraiser);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FundraiserExists(int id)
        {
          return (_context.Fundraiser?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        //Return donation view when "Donate" button is clicked
        public async Task<IActionResult> Donate(int? id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Donate(int id, [Bind("Id,amount,donateDate,userName,cardNum,fundraiserId")] Donation donation, Fundraiser fundraiser)
        {
            var rand = new Random();
            if (ModelState.IsValid)
            {
                donation.Id = rand.Next();
                donation.fundraiserId = id;
                _context.Add(donation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(donation);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fundraisers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/CS451R_Fundraiser.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <!-- ===== Begin Header ===== -->
    <header>
        <a id="blogo" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/blastOffRocket.png" height="100px" width="100px" /></a>
        <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Fundraisers" asp-action="Index">Fundraisers</a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link row" asp-area="" asp-controller="Fundraisers" asp-action="Create">Launch a Fundraiser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link row" asp-area="" asp-controller="Home" asp-action="Dashboard">User Dashboard</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <!-- This loads the content based on the page you are on. Remains within overall layout. -->
    <div class="wrapper">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ===== Begin Footer ===== -->
    <footer id="footer" class="border-top footer">
        <div class="container">
            <h3>BlastOff</h3>
            <div class="credits"> Design by: Andrew Hemenway | Arya Yazdi | Kyle Helm | Riley Brookins</div>
            <div class="copyright">&copy; Copyright Blast Off Inc. 2023 All Rights Reserved</div>
        </div>
    </footer>
    <!-- ===== End Footer ===== -->


    <!-- ===== JS & Bootstrap Files ===== -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>